apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: echo
        image: casi/http-echo:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: echo
