apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: echo

commonAnnotations:
  app: echo

namePrefix:
  kustom-

nameSuffix:
  -v1

configMapGenerator:
- name: echo
  env: config.properties
